### ISSUE TITLE
Exclude build directory

### ISSUE THREAD

**Issue by tmvkrpxl0** [abdmoh1232/enderium-mod#4]
Hello, It seems like build directory of this repository contains Minecraft source code
I feel like it shouldn't exist in this repository, so could you delete it?

**Comment by abdmoh1232** [comment]
I'm not experienced with modding with forge I'm assuming that you meant the compile_java folder right?

**Comment by tmvkrpxl0** [comment]
Well, best practice is to remove whole build directory. It is temporary directory and sometimes it may contain things that will only work on a specific pc

**Comment by tmvkrpxl0** [comment]
Or.. delete whole commit history, by deleting current repository and re-uploading it without build directory

**Comment by abdmoh1232** [comment]
ok I made a new repository without all the unecessary directories. You can find it on the curseforge page or through this link: https://github.com/abdmoh1232/enderium
Thanks for your help and let me know if you have more issues on the new repository!
